# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sneakers_development
  pool: 5
  username: root
  password: xgcwahti 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sneakers_test
  pool: 5
  username: root
  password: xgcwahti 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sneakers_production
  pool: 5
  username: root
  password: xgcwahti 

